# This is a GNU makefile

PREFIX := /usr/local/encap/garlicGeneralPrograms-0.0

BIN = $(PREFIX)/bin

CFLAGS = -g

scripts = gar_pushSshKeys

bins = $(scripts)

build:

install:
	mkdir -p $(BIN)
	cp $(bins) $(BIN)/


clean:

