#!/bin/bash

dtk-floatSliders joystick\
 -N 2\
 -s 0 -1.1 1.1 0\
 -s 1 -1.1 1.1 0\
 -l x y &

dtk-floatSliders wand\
 -N 6\
 -s 0 -1.5 1.5 0\
 -s 1 -1.5 1.5 0\
 -s 2 -1.5 1.5 0\
 -s 3 -190 190 0\
 -s 4 -190 190 0\
 -s 5 -190 190 0\
 -l x y z H P R &

