#!/bin/bash

# This we learned by trial and error is how we run Unity
# after we install it via gdebi
# See /usr/local/src/Unity (if you can) for details.

cd /opt/Unity/Editor || exit 1
exec ./Unity || exit 1

# Should never get to here.
