#!/bin/bash

######################################
# defaults
######################################

root=/NTFS/Shared/demos
host=cube
rhost=$(hostname)
mono=
run_stop=" --on_exit hy_stop"
just_server=

######################################

function usage()
{
    cat << EOF

  Usage: $0 [SERVER_HOST][-m|--mono][--no-stop][--just-server]\
      [--with-term [args ...]]|[-h|--help]

  Run the hyperCube demoRunner.


          OPTIONS


    -h|--help        Print this help and exit
    
    --just-server    Just run the demoRunner server

    -m|--mono        Run programs with mono visuals (not stereo)

    --no-stop        Don't run hy_stop after quiting.  hy_stop stops the
                     X session and turn off projects.

    --with-term      Run this program in a xfce4-terminal with the
                     remaining arguments passed to xfce4-terminal

    SERVER_HOST      Run the nodejs demoRunner server on SERVER_HOST.
                     That's for testing.

EOF

    exit 1
}


function catch()
{
    echo "caught signal, sending QUIT request"
    set -x
    ssh $host wget --no-check-certificate\
 https://$host:8383/QUIT?passcode=${passcode}\
 -O -
    set +x
    # That should tell the server to quit
    # If that failed, too bad.
}

passcode=$(openssl rand -hex 3)

function runServer()
{
    local heading="HyperCube Demos in stereo"

    env_opts=" "

    if [ -n "$mono" ] ; then
        env_opts=" INSTANTPLAYER_CAVE_OPTIONS=--mono HYPERCUBE_OPTIONS=--mono"
        heading="HyperCube Demos in mono"
    fi

    local exe=

    if [ -n "$just_server" ] ; then
        exe="exec "
    fi

    if [ "$rhost" != "$host" ] ; then
        exe="$exec ssh $host -X"
        heading="\"$heading\""
    fi

    # If there is an old server running tell it to quit.
    ssh $host wget\
 http://localhost:8080/QUIT?foo=bar -O -

    set -x
    if ! ${exe}${env_opts}\
 webLauncher --root_dir $root\
 --title Demos\
 --exit_on_last 6000\
 --kill_children\
${run_stop}\
 --passcode $passcode\
 --catch_signal SIGINT\
 --heading "$heading" ; then
        exit 1
    fi
    set +x
}


# I guess this assumes that you are using a bash shell on $host
if ! ssh $host "if [ ! -d $root ] ; then exit 1 ; fi" ; then
    root=/usr/local/src/webLauncher
    echo "Setting server doc root to: $root"
fi

script_args=

while [ -n "$1" ] ; do
    if [ "$1" != "--with-term" ] ; then
        script_args="$script_args $1"
    fi
    case "$1" in
        --no-stop)
            run_stop=
            ;;
        --just-server)
            just_server=yes
            ;;
        -m*|--m*)
            mono=--mono
            ;;
        --with-term)
            shift 1
            # rerun in a terminal
            set -x
            exec xfce4-terminal --geometry 100x32-0+0 -e "$0 $script_args $*"
            ;;
        -*)
            usage
            ;;
        *)
            host=$1
            ;;
    esac
    shift 1
done

echo "host=$host rhost=$rhost"


if [ "$host" != "$rhost" ] ; then
    if ! gar_pushSshKeys $host ; then
        echo
        echo "FAILED to check ssh keys"
        echo
        exit 1
    fi
fi


if [ -n "$just_server" ] ; then
    runServer
    exit 1
fi

runServer &


count=0
# wait for server to be working via a netcat connect.
while ! nc -z $host 8383 ; do
    sleep 0.6
    echo "wanting to server to start"
    let count=$count+1
    if [ "$count" = "20" ] ; then
        echo "Failed to connect to server"
        sleep 100
        exit 1
    fi
done


echo "server is running"

# We wish to have signal control of the server

trap catch SIGINT SIGTERM SIGQUIT

echo "passcode=$passcode"

set -x
firefox https://$host:8383/?passcode=${passcode}
set +x


while true ; do
    # TODO: Fix this crap!   I don't like this
    # server polling shit.
    # Getting a PID to wait on was a problem.
    # If the server is not running exit
    if ! nc -z $host 8383 ; then
        echo "Server is unreachable"
        sleep 10 # let the user see the spew
        exit
    fi
    sleep 6
done

