#!/bin/bash -x

######################################
# defaults
######################################

root=/NTFS/Shared/demos
host=cube
rhost=$(hostname)
mono=

######################################

rhost=console.sv.vt.edu

function usage()
{
    cat << EOF

  Usage: $0 [SERVER_HOST][-m|--mono]|[-h|--help]

  Run the hyperCube demoRunner.


          OPTIONS


    -h|--help      Print this help and exit

    -m|--mono      Run programs with mono visuals (not stereo)

    SERVER_HOST    Run the nodejs demoRunner server on SERVER_HOST.
                   That's for testing.

EOF

    exit 1
}


function catch()
{
    if [ -n "$server" ] ; then
        echo "killing server pid $server"
        kill $server
        server=
    fi
}

function runServer()
{
    local heading="HyperCube Demos in stereo"

    env_opts=" "

    if [ -n "$mono" ] ; then
        env_opts=" INSTANTPLAYER_CAVE_OPTIONS=--mono HYPERCUBE_OPTIONS=--mono"
        heading="HyperCube Demos in mono"
    fi

    if ! ssh\
 $host -X${env_opts}\
 demoRunner-server $root\
 --remote $rhost\
 --title Demos\
 --exit-on-last\
 --kill-children\
 --heading \"$heading\" ; then
    exit 1
fi
    
}


# I guess this assumes that you are using a bash shell on $host
#if ssh $host "if [ ! -d $root ] ; then exit 1 ; fi" ; then
#    root=/usr/local/src/demoRunner/testDocRoot
#fi


while [ -n "$1" ] ; do
    case "$1" in
        -m*|--m*)
            mono=--mono
            ;;
        -*)
            usage
            ;;
        *)
            host=$1
            ;;
    esac
    shift 1
done

if ! gar_pushSshKeys $host ; then
    echo
    echo "FAILED to check ssh keys"
    echo
    exit 1
fi

runServer &

server=$!


count=0
# wait for server to be working
while ! nc -z $host 8080 ; do
    sleep 0.3
    let count=$count+1
    if [ "$count" = "50" ] ; then
        echo "Failed to connect to server"
        kill $server
        exit 1
    fi
done


echo "server is running"

# We wish to have signal control of the server

trap catch SIGINT SIGTERM SIGQUIT

firefox http://$host:8080/ &

wait $server


if [ "$host" != "$rhost" ] ; then
    ssh $host /usr/local/bin/hy_stop
else
    /usr/local/bin/hy_stop
fi

