#!/bin/bash

# This was for the most part copied from 
# Paul Rajilich of visbox.com, file:
# NVIDIA-ENABLE-FRAMELOCK.sh

# See Nvidia README Chapter 30F /usr/share/docs/NVIDIA_GLX-1.0/README.txt

if [ -n "$1" ] ; then
    cat << EOF
  Usage: $0"

  Enable nvidia frame locking for all 4 nvidia graphics cards.  See
  also: "hy_frameLock_off -h"

  Without framelocking enabled there may be image tearing between
  adjacent screens.

EOF

fi

set -x
export DISPLAY=:0.0

# set master (LTL)
nvidia-settings -a [gpu:0.dpy:DP-0]/FrameLockDisplayConfig=2

# set slaves (other 15 outputs)
nvidia-settings -a [gpu:0.dpy:DP-2]/FrameLockDisplayConfig=1
nvidia-settings -a [gpu:0.dpy:DP-4]/FrameLockDisplayConfig=1
nvidia-settings -a [gpu:0.dpy:DP-6]/FrameLockDisplayConfig=1
nvidia-settings -a [gpu:1.dpy:DP-0]/FrameLockDisplayConfig=1
nvidia-settings -a [gpu:1.dpy:DP-2]/FrameLockDisplayConfig=1
nvidia-settings -a [gpu:1.dpy:DP-4]/FrameLockDisplayConfig=1
nvidia-settings -a [gpu:1.dpy:DP-6]/FrameLockDisplayConfig=1
nvidia-settings -a [gpu:2.dpy:DP-0]/FrameLockDisplayConfig=1
nvidia-settings -a [gpu:2.dpy:DP-2]/FrameLockDisplayConfig=1
nvidia-settings -a [gpu:2.dpy:DP-4]/FrameLockDisplayConfig=1
nvidia-settings -a [gpu:2.dpy:DP-6]/FrameLockDisplayConfig=1
nvidia-settings -a [gpu:3.dpy:DP-0]/FrameLockDisplayConfig=1
nvidia-settings -a [gpu:3.dpy:DP-2]/FrameLockDisplayConfig=1
nvidia-settings -a [gpu:3.dpy:DP-4]/FrameLockDisplayConfig=1
nvidia-settings -a [gpu:3.dpy:DP-6]/FrameLockDisplayConfig=1

# enable framelock on all GPUs
nvidia-settings -a [gpu:0]/FrameLockEnable=1
nvidia-settings -a [gpu:1]/FrameLockEnable=1
nvidia-settings -a [gpu:2]/FrameLockEnable=1
nvidia-settings -a [gpu:3]/FrameLockEnable=1

