#!/bin/bash


if [ -n "$1" ] ; then
    cat << EOF
  Usage: $0"

  Enable nvidia sync to VBlank.

EOF

fi

set -x
export DISPLAY=:0.0

nvidia-settings --load-config-only --assign="SyncToVBlank=1"

echo "$0 finished"
