#!/bin/bash


###########################################################
#          CONFIGURE resolution
###########################################################
# These xorg.conf files need to be installed in /etc/X11/
# then we can select which resolution we want to run with

# pick one XORGCONFIG
default_conf=xorg.conf.cube_2560x1600
#default_conf=xorg.conf.cube_1920x1200

###########################################################

export XORGCONFIG="${XORGCONFIG:-$default_conf}"
echo "XORGCONFIG=${XORGCONFIG}"


function usage()
{
    cat <<EOF

  Usage: $0 [-h|--help]

  Run a xfce user desktop X session; just like logging in at a desktop
  locker, but without looking at the desktop X11 screen.

  This just runs 'startx'.  That's the correct way to start an X11 when
  there is no locking login window manager.

  You can run with lower resolution 1920x1200 pixel per root window by
  setting env XORGCONFIG=xorg.conf.cube_1920x1200 .

EOF
    exit 1
}

[ -n "$1" ] && usage


set -x
startx &

# Trial and error shows that signaling the startx process will
# not alway stop the X session, but signaling x-session-manager
# seems to be the correct thing to do.  So now we must find the
# process id (PID) of the x-session-manager.  Then again why
# bother looking for this PID here, just let killall do the work,
# it's the same. See hy_stopx
