#!/bin/bash

ret=0

function usage()
{
    cat <<EOF

  Usage: $0 [-h|--help]

  Run programs needed to stop a HyperCube session.

  Runs the following 3 programs:
      
       hy_kill_dtk-server     kill any dtk-server programs
       hy_stopx               turn off all user X sessions 
       hy_projectors_off      turn off the projectors

EOF

    exit 1
}

function Run()
{
    if ! $* ; then
        echo
        echo "$* FAILED"
        let ret=$ret+1
    fi
}


while [ -n "$1" ] ; do
    case $1 in
        -h|--h*|*)
            usage
            ;;
    esac
    shift 1
done

Run hy_kill_dtk-server
Run hy_projectors_off
Run hy_stopx

echo "$0 finished with return status $ret"

exit $ret
